// Code generated by entc, DO NOT EDIT.

package auth

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the auth type in the database.
	Label = "auth"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserid holds the string denoting the userid field in the database.
	FieldUserid = "userid"
	// FieldRfUUID holds the string denoting the rf_uuid field in the database.
	FieldRfUUID = "rf_uuid"
	// FieldIsBlocked holds the string denoting the is_blocked field in the database.
	FieldIsBlocked = "is_blocked"
	// FieldRfToken holds the string denoting the rf_token field in the database.
	FieldRfToken = "rf_token"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldExpireAt holds the string denoting the expire_at field in the database.
	FieldExpireAt = "expire_at"
	// Table holds the table name of the auth in the database.
	Table = "auths"
)

// Columns holds all SQL columns for auth fields.
var Columns = []string{
	FieldID,
	FieldUserid,
	FieldRfUUID,
	FieldIsBlocked,
	FieldRfToken,
	FieldCreatedAt,
	FieldExpireAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsBlocked holds the default value on creation for the "is_blocked" field.
	DefaultIsBlocked bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
